# Generated by cucumber-sinatra. (Fri Oct 01 07:58:05 -0500 2010)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Capybara.app = App

class AppWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  AppWorld.new
end
